services:
  postgres:
    image: bitnami/postgresql
    container_name: todos-postgres
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: todos
    ports:
      - "5434:5432"
